services:
  postgres:
    image: postgres:latest
    restart: always
    env_file: vars.env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - net-postgres-db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - net-postgres-db
volumes:
  postgres_dbdata:
    driver: local

networks:
  net-postgres-db:
    driver: bridge
